/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    experiences: Experience;
    skills: Skill;
    technologies: Technology;
    categories: Category;
    companies: Company;
    schools: School;
    education: Education;
    testimonials: Testimonial;
    messages: Message;
    journal: Journal;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    education: EducationSelect<false> | EducationSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    journal: JournalSelect<false> | JournalSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    settings: Setting;
    hero: Hero;
    about: About;
    contact: Contact;
    navigation: Navigation;
    footer: Footer;
    'sections-visibility': SectionsVisibility;
    'sections-content': SectionsContent;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'sections-visibility': SectionsVisibilitySelect<false> | SectionsVisibilitySelect<true>;
    'sections-content': SectionsContentSelect<false> | SectionsContentSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Comptes autorisés à se connecter à cet espace d’administration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images, logos et vidéos réutilisables un peu partout sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Projets du portfolio affichés dans la section projets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  /**
   * Variante facultative de l’image de couverture pour le mode sombre. Elle remplace l’image de couverture quand le site est en mode sombre.
   */
  coverImageDark?: (number | null) | Media;
  /**
   * En haut de la page du projet, affiche la capture ci-dessous dans un cadre d’appareil à la place de l’image de couverture. Les cartes continuent d’utiliser l’image de couverture (le logo).
   */
  mockupFrame?: ('none' | 'phone' | 'desktop' | 'custom') | null;
  /**
   * Image ou vidéo affichée dans le cadre — une vidéo est lue en boucle, sans son. Idéalement au format de l’appareil : vertical (9:19,5) pour l’iPhone, 16:10 pour le MacBook. Avec « Image déjà en mockup », déposez plutôt le montage terminé, de préférence en PNG sur fond transparent. Sans fichier, l’image de couverture est affichée comme avant.
   */
  mockupImage?: (number | null) | Media;
  /**
   * Variante facultative pour le mode sombre, si l’application ou le site a un thème sombre.
   */
  mockupImageDark?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  technologies?: (number | Technology)[] | null;
  githubUrl?: string | null;
  liveUrl?: string | null;
  featured?: boolean | null;
  /**
   * Les projets privés restent dans le CMS mais ne sont jamais affichés sur le site.
   */
  visibility: 'public' | 'private';
  /**
   * Ordre d’affichage : 1 s’affiche en premier, 2 en deuxième, etc. Laissez vide pour classer le projet après ceux qui sont ordonnés, du plus récent au plus ancien.
   */
  order?: number | null;
  year?: number | null;
  status?: ('live' | 'in-progress' | 'archived') | null;
  category?: (number | null) | Category;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Taille maximale : 12 Mo. Idéalement moins de 500 Ko par image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Étiquettes de technologies utilisées par les projets et les expériences.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Inverse les couleurs du logo quand le site est en mode sombre. À activer pour les logos noirs ou foncés, afin qu’ils restent visibles sur le thème sombre.
   */
  invertLogoInDarkMode?: boolean | null;
  website?: string | null;
  /**
   * Couleur hexadécimale facultative, affichée en petit point sur les puces de technologies, par exemple #4287F5 (le # est ajouté automatiquement s’il manque).
   */
  color?: string | null;
  category?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catégories partagées par les compétences, les technologies, les projets et le journal. Regroupées par domaine pour que chaque collection ne propose que les catégories qui la concernent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  group: 'tech' | 'project' | 'journal';
  /**
   * Ordre d’affichage au sein du groupe : 1 s’affiche en premier, 2 en deuxième, etc. Les catégories sans valeur passent en dernier, triées par nom.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entrées de la frise des expériences professionnelles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  company: number | Company;
  position: string;
  employmentType?: string | null;
  location?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  technologies?: (number | Technology)[] | null;
  startDate: string;
  endDate?: string | null;
  currentlyWorking?: boolean | null;
  /**
   * Ordre d’affichage : 1 s’affiche en premier, 2 en deuxième, etc. Laissez vide pour classer l’entrée après celles qui sont ordonnées, de la date de début la plus récente à la plus ancienne.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entreprises référencées par les expériences professionnelles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  location?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Compétences regroupées par catégorie, affichées dans la section compétences.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  name: string;
  category: number | Category;
  /**
   * Lien facultatif vers la documentation ou le site officiel. Rend toute la carte cliquable.
   */
  url?: string | null;
  logo?: (number | null) | Media;
  /**
   * Inverse les couleurs du logo quand le site est en mode sombre. À activer pour les logos noirs ou foncés, afin qu’ils restent visibles sur le thème sombre.
   */
  invertLogoInDarkMode?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Écoles référencées par les entrées de formation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  location?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Entrées de la frise des formations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education".
 */
export interface Education {
  id: number;
  school: number | School;
  degree: string;
  fieldOfStudy?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  startDate: string;
  endDate?: string | null;
  currentlyStudying?: boolean | null;
  /**
   * Ordre d’affichage : 1 s’affiche en premier, 2 en deuxième, etc. Laissez vide pour classer l’entrée après celles qui sont ordonnées, de la date de début la plus récente à la plus ancienne.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Citations de clients et de collègues affichées dans la section témoignages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Nom complet de la personne qui témoigne.
   */
  author: string;
  /**
   * Intitulé du poste, par exemple « Product Manager ».
   */
  role?: string | null;
  company?: (number | null) | Company;
  avatar?: (number | null) | Media;
  quote: string;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages envoyés depuis le formulaire de contact du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  email: string;
  message: string;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Récits personnels, hors technique : voyages, sport, réussites, événements, découvertes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal".
 */
export interface Journal {
  id: number;
  title: string;
  slug: string;
  category: number | Category;
  shortDescription: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  date: string;
  location?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Les entrées privées restent dans le CMS mais ne sont jamais affichées sur le site.
   */
  visibility: 'public' | 'private';
  /**
   * Ordre d’affichage : 1 s’affiche en premier, 2 en deuxième, etc. Laissez vide pour classer l’entrée après celles qui sont ordonnées, de la date la plus récente à la plus ancienne.
   */
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Taille maximale : 12 Mo. Idéalement moins de 500 Ko par image.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'technologies';
        value: number | Technology;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'schools';
        value: number | School;
      } | null)
    | ({
        relationTo: 'education';
        value: number | Education;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'journal';
        value: number | Journal;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  coverImage?: T;
  coverImageDark?: T;
  mockupFrame?: T;
  mockupImage?: T;
  mockupImageDark?: T;
  gallery?: T;
  technologies?: T;
  githubUrl?: T;
  liveUrl?: T;
  featured?: T;
  visibility?: T;
  order?: T;
  year?: T;
  status?: T;
  category?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  company?: T;
  position?: T;
  employmentType?: T;
  location?: T;
  description?: T;
  technologies?: T;
  startDate?: T;
  endDate?: T;
  currentlyWorking?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  url?: T;
  logo?: T;
  invertLogoInDarkMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  invertLogoInDarkMode?: T;
  website?: T;
  color?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  location?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  location?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education_select".
 */
export interface EducationSelect<T extends boolean = true> {
  school?: T;
  degree?: T;
  fieldOfStudy?: T;
  description?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  currentlyStudying?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  company?: T;
  avatar?: T;
  quote?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal_select".
 */
export interface JournalSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  content?: T;
  coverImage?: T;
  gallery?: T;
  date?: T;
  location?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  featured?: T;
  visibility?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité, image de marque, contact, thème et SEO par défaut, utilisés sur tout le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  name: string;
  profession?: string | null;
  photo?: (number | null) | Media;
  logo?: (number | null) | Media;
  /**
   * Définit la couleur utilisée pour les boutons, les liens, les badges, les états de focus et les accents sur tout le site.
   */
  theme: {
    /**
     * La couleur d’accent principale, utilisée partout sur le site.
     */
    primaryColor:
      | 'orange'
      | 'coral'
      | 'red'
      | 'crimson'
      | 'rose'
      | 'pink'
      | 'purple'
      | 'violet'
      | 'indigo'
      | 'blue'
      | 'sky'
      | 'cyan'
      | 'teal'
      | 'mint'
      | 'emerald'
      | 'green'
      | 'lime'
      | 'olive'
      | 'gold'
      | 'amber'
      | 'yellow'
      | 'slate'
      | 'gray'
      | 'neutral';
    /**
     * Couleur secondaire facultative, pour un léger dégradé bicolore en arrière-plan. Si elle est vide, la couleur principale est utilisée.
     */
    accentColor?:
      | (
          | 'orange'
          | 'coral'
          | 'red'
          | 'crimson'
          | 'rose'
          | 'pink'
          | 'purple'
          | 'violet'
          | 'indigo'
          | 'blue'
          | 'sky'
          | 'cyan'
          | 'teal'
          | 'mint'
          | 'emerald'
          | 'green'
          | 'lime'
          | 'olive'
          | 'gold'
          | 'amber'
          | 'yellow'
          | 'slate'
          | 'gray'
          | 'neutral'
        )
      | null;
    defaultTheme?: ('light' | 'dark' | 'system') | null;
    /**
     * Curseur personnalisé affiché sur ordinateur. Automatiquement désactivé sur les écrans tactiles et pour les personnes qui préfèrent réduire les animations.
     */
    cursorEffect?: ('ring' | 'trail') | null;
  };
  contactEmail?: string | null;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'instagram' | 'dribbble' | 'other';
        url: string;
        /**
         * Icône personnalisée facultative. Si elle est vide, l’icône intégrée de la plateforme choisie est utilisée.
         */
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Métadonnées de secours, utilisées quand une page ne définit pas les siennes.
   */
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    defaultImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La bannière d’accueil, en haut de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Ajoutez un fichier par langue. Le bouton n’apparaît que lorsqu’un fichier est défini pour la langue affichée, et pointe directement dessus.
   */
  resumeCta?: {
    label?: string | null;
    file?: (number | null) | Media;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Taille maximale : 12 Mo. Idéalement moins de 500 Ko par image.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La section « à propos » de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Listes titrées affichées à côté du portrait — par exemple Soft skills, Centres d’intérêt, Voyages, Parcours sportif.
   */
  pointGroups?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  portrait?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La section contact de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  eyebrow?: string | null;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  successMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Liens de navigation principaux, dans l’en-tête.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texte et liens du pied de page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  text?: string | null;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Choisissez les sections affichées sur le site. Une section désactivée disparaît de la page d’accueil, de la navigation et, pour le journal, de ses pages dédiées.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-visibility".
 */
export interface SectionsVisibility {
  id: number;
  /**
   * Affiche ou masque la section Bannière sur tout le site.
   */
  hero?: boolean | null;
  /**
   * Affiche ou masque la section À propos sur tout le site.
   */
  about?: boolean | null;
  /**
   * Affiche ou masque la section Projets sur tout le site.
   */
  projects?: boolean | null;
  /**
   * Affiche ou masque la section Expériences sur tout le site.
   */
  experience?: boolean | null;
  /**
   * Affiche ou masque la section Formations sur tout le site.
   */
  education?: boolean | null;
  /**
   * Affiche ou masque la section Compétences sur tout le site.
   */
  skills?: boolean | null;
  /**
   * Affiche ou masque la section Témoignages sur tout le site.
   */
  testimonials?: boolean | null;
  /**
   * Affiche ou masque la section Contact sur tout le site.
   */
  contact?: boolean | null;
  /**
   * Affiche ou masque la section Journal sur tout le site.
   */
  journal?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Surtitre, titre et description affichés au-dessus des sections Projets, Expériences, Formations, Compétences, Témoignages et Journal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-content".
 */
export interface SectionsContent {
  id: number;
  projects: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  experience: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  education: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  skills: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  testimonials: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  journal: {
    eyebrow?: string | null;
    title: string;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  name?: T;
  profession?: T;
  photo?: T;
  logo?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        defaultTheme?: T;
        cursorEffect?: T;
      };
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  highlights?:
    | T
    | {
        value?: T;
        id?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  resumeCta?:
    | T
    | {
        label?: T;
        file?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  body?: T;
  pointGroups?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  portrait?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  text?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-visibility_select".
 */
export interface SectionsVisibilitySelect<T extends boolean = true> {
  hero?: T;
  about?: T;
  projects?: T;
  experience?: T;
  education?: T;
  skills?: T;
  testimonials?: T;
  contact?: T;
  journal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections-content_select".
 */
export interface SectionsContentSelect<T extends boolean = true> {
  projects?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  experience?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  education?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  skills?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  journal?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}